NyRsMidxGIuVHTPPrFbrrEoZKIZsHiDVaEfOlejBTsrTTkmBdbvlMNOXpvuQjHFAqDPMvrIokBMIcXh226 = "jYXGtgUKzfSFcJSqmIkFmfiEfacXbupAJRQUvxebFuGuvsCTzMrpIiPWGMPjRQklhCmVrfbCCYcnjwI"
AaAaaaAaAAaAAAaAAaaAaaaaaAAaaAaaAaAaaaaaaAAAaAaaaAaAAaAAAaAAaAAAAAAAaaAAAAaAAAAaAaaAAAaaaaAAAaaAaAaAaaAAAAaaAaaaaAaAaaAaAAAaAaAaaAAaaaaAAaAAAAAAAaaaaaaAaAAaAaAaAaaAaAaAAaAAaAAAAaAAaaaAAaAAAAaaaaAaaAaaAaAAaAAaAAAaaAaAaaaAaaAA = "yXZXHHeyBZFjHFYIBoKFKrLvrICCPeSvDbvvryYnEbQmfepyscBbgcRDwRyxEMCpVqVWsKczMZmKEMZ"
X222 = 241
k220 = 481
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = "wMpIKylOHFKqnWScEFrnMJGLpWoIhNYyipPCkUBZEvAMvkUaGCUDFHqnMNDdKIMqHMhOfFecGLAuFxa"
mMnmKdVwsCoaTuZWqrxWBoWWFLKfDnFVzzzbVPCvqEfRlaADmUYSXtbRUSQvuVrOcmYvZsmtbOFUKsG216 = "WPpEoQiAXvHDnAitYcBLysYcqjgPnxiWRyBcnYvRKfBxzoxdIxPFsxYpnZmWfrPJfcDQZsUOmedqxUP"
j214 = 473
vqIOGeCSYvJIAdCWllKlKASFvxKSwSokeKhSGOfExvUYRLYsKkBUOfsHwMlOPpfFKtLxzUKhVxPCERB212 = "DhCopBTQTLOHvBhCZaBhUnwlTsmHpVnVeWZmGRIMqcvydapdSWIdCvmlnljxRKZKZDDuBPsphfaxvYx"
MJpggLjnboOYFyKmCMXCsQxTwFqKYUIAseaGQAkRPKMDgCeeczOHtpwBxYcKDlOCNnBAubIbBNWdEVz210 = 405
gcPsLingWzqNlRYEFdesPjZNFplXcQrtRofIbfbabjyKHRjazgbjiwkyHwhEcyfZzweBizByfYqdebW208 = 445
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK = 292
ducPepCCJcOLomBFetCcewuFSOeirsAuJpxQBVkqMmQaWNBwMfRjuCaMgzrpJarsauPiwdzDUeUowiJ204 = "TbneRmisKXWHcTRbFnulqZhYQKazosyviWhKitxqLQHKJbOYGCVkIAiXWOdhGZloOfHEYyBRwChAioL"
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN = 362
J16634652448930988200 = "UKrNWXmyJxGTBheOyVlTQVfZvFdTqakzxZgSnRqpmIzkyfITMPNTHhAEQVBGOxtdtVGOlIKOUEgSSwH"
aaaaaaAAAaaaaaAaaaAaAaaaaAaAaaaAAaaAAaaAAAAaaaaaaaAaaAAAaAaAaAAaaAaAAaaAAAAaAAaAaAaAAaaaaaAaaaAaAaAaaaaaAaAAAAaAAAAAAaaAAaaAaAaaaAAaaAaAaaaAAAAaaaaAAaaAAAaAAaaAAaaaAaaAAAAAaAaAAaAaAAAaaAAAaaAAAaAAaa = 357
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = "TCnaTALCUftJSTTnulEEcCjSfBybOCHagBCIpXPBvCGuphiIsSRAQFywnWDYgDYEhjbZYmhCAlOcBiV"
i16634652448871691194 = "CIuGylRVcMcnbzcQlOPhQgozekywMMldIrfijmWRVqLQdTbNaiPpvoUerTazXhCpGjSvXXBawOzzqho"
IIlIIllIlllllIIIIllIlIIIIIIlIIIIlIlllIllllllIlllIlIlIlllIlIIIlIIIllIllIIllIIlIllIIllIlllIllIlllIIIIIllIIllllIlIlllIlIlIlIlIIllIIIIIlIIllllIIIIlIlIIlIlIIIIlllIlIllllllllllIIIllIlIlIllIIIIlIIllI = 607
w190 = "nNzkVVwFeLtVnvsAKAenQUBHGiLVVnnDwGQHZwWAgGAutKfecEMkURdznCKiizRVxHzSoOhURWnIFkV"
aaaAaAAaAAAaaAAaaAaAAAaaAAAAAaAaAAAAAAAAaaAaAAaaAAAAAaAaAaAAaaaAAaAAAAaAAaaaAaaAaAaaAaAaAAAaaaAAAAaAAAaAAaAaAAaaAAAAAAaAAaAaaaaAaAAaAaAAAAAAAaAaAaaaaAAAAaaAaAAAaAAaAaaAaAAAaAAAaAaAAaaaaAaA = 710
AaAAaAaaAaAaAaaAaAaAAAAaaaAaAAAaaAAaAAaAaAAaAaAaAaaaaaaAaAAAAaaaaaaAaaaaAAaAAaaaaAAAaAAAAaaAaAAAaAaAaaAAAaAAaaaAAaaAAAaaaAaAaaAAAaaaaAaaAaaaaAAAaAAAaAAAAaAAaAAaaaaAAAAaAAAaaAaAAaaaAAaaaA = "uhorhsmquJmVgmvpDWSXVWSelsjOMtiGwjuMxFkMgPPXEKEJBjEdXPBSOQpLaZgCvvvTWYACrFjNyPy"
zxcLOJTYzVcMoqQerynKJYQESQlacqhAUERbNiAEnLsXQOYOFWEtaOIjazWODQvMwNHasroMSocoWwL184 = "mZOMtjJNfDORILbdFDNRPZJBfrIAgAPlBWjKLnCIoNtxpWXVpDWKoCwoFAsxoCAOOoYEoJgJCtpTRwZ"
lIIIlIlIlIIIllIlIIIIllllIIlIllIlIlIlIIlIIIIllIIIIllIIIlIIllIIIIIllllIIlIIIlllIIlllIIllllIlllIIIlIIIIlllIIIIlIIlllIllIllIIIIlIllIlllIIlIlIIIIlllIllIlIIlIlIIllIlIIIIlIIIlIllllIllllIIIl = "WOFpZxaeoNeeErKfRMXyTdqOeZJLZRyiHqXqFjkQpdCtVYKIOybGuryvrFmbNswcARomlHSLeTqmcck"
t180 = "LCWinaGVKYbwTSAvVdtGfGGXDffpdjmeQettCvKQVUMEmBbOdEyzvHFvfTklSoxTRIOFyGKygdrZCEB"
dCraVUBQomLQigwPYzulKDaaTUFYEigpGuFmVFAKKtEUkFfYNLUfVUpPfjRnmUlJIxgAlFpWDUoETmc178 = 252
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh = 522
IllllllllIlIIIIllllIIIIIlIlIlllIlIIllIIIlIlIlIIIIIIlIIIIlIIIIIlIIIIlIIllIlIllIllllIlIIlllllllIlllIlIIllllllIlIlIlIllIlllIlllIIIlIIIIIIIIlllIllIlllIIIlllllllIllIIIlIlllIIlIlIl = 159
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 373
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = 839
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = "nwfXdeCKfYtqKqWnacwndhvmKqwcjaYoUzydshVzPNFuzrEOFeWkqggVRklyQrrlRlIZYdrUgtOgceB"
aAaaaAaaaaAaAaAaAaaAAAaaaAAAaaAAaAAaAaaaaAaAaAaaAAAAAAAaAAaAaAaaaaAaAAaaaaaAaAaAaaaAaaAAAAaaAAAaAaaaAaaAAaaAAaAaaaaAaAAaaaaaAaaaaAaaAaaaAAaAAaAAAaAaaAaAaaaaaAaaaAAaaa = "ZfxyvnsNdGqJkyGbEQPJKTINpzAgNujrjxdzlQcXxtsAZXWfkwbMueBmXzRAJbGnHiHEVKHCnjnCkYu"
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV = 288
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh = 333
llllIIIlIIIIlIlIIIIlIlllIIllIlllIlllIllIIIIIlIlIIIlIIlIIIIlIlIIlllIlllIlIlIlIIlIIIlllIIIIIllIIIIllIIIllIIIlIIIlIIlIIlllllIIIlIlIIIIlIlIllIlIIIIIIllIIIlIIIlIIlll = 187
yemclOglWtCJTyvybSdxxDhIZVGlGGAyeWMgMrBMkmntybAjCwpsKbDMbkPmDriBJANsaYQgLjBVnNy158 = 424
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = 350
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq = "nPMqAAepFHyzhqvvSbiWSxqOftwffYqFdltUYYayEMZFkEsMnCrnzNSPuzaXdZvOXCcbvaSiHqXgSVI"
P152 = "OgbElbUuyYIrpDSpWhbEYwYrEmYEKzNMSKTeArBexJDRQHESgJHvLdfZPzkiLGxcmKjbLmCDJxiGUNa"
ZtDMyidjXHIMnygcSribcZiqonNhejLqpqTokUaVMlajFpgLURTZdqHHuNfkpYSHQoPmtngdrDOVFKe150 = 304
AaAaAAaAAaAaAaaaaAAaaAaaaAaaAAaAaAAaAaAaAAaaaAaaAAAAAAaaAAAaaaaaaAaAaAaaAaaaaAAaAAaAAAAAAaAaAaaaAAaAaaAaAAaAaAaAAaAaAaAaaaAaAAAaaAaaaaAAaAaaaaaAAAaA = "jodqnMENNGGvYJcSBhJfgSqSvdJDVcnhRWodEEnXXcYaWlPzQRAelVKUxpprkIQbiCGLCuidVuamBFI"
llllllIIIllIlIlllIIlIIlIIIlIlllIlIlllIIllllIlIlIlllIIlIIlIlIIIIIIlIlIIIllIlIIllIllIlIlIllIlIlllllIlllIlIllllllIlIIIlIlllIIIlIIlIlIIIIIIIIlIlIlIllI = 554
AaAAAaAaaAaaaAaAaaaaAaAAaaAAAaaAaaaaAAAAaaaaaaAAAaaaaaAAaAAAaaaaaaaAAAaAaaAAaaAAaAaAaAAaAaAaaAAaaaAAAAAaAaAaAaaaaAaAaAaaAaAaAaaaAaAAaaAAAAaaaaaA = 457
aAAAaaaAaAaaAAAAaaaaAAAAAAaaAaaaaAAaAaaaAAaaAAaaaaaAaaaAAAaaaaaaAaaaAAaaAAaaAAAaaaaAAAaaaaAaaaAAaAaAaAaAAAAAAaAaAAAAaaaAaAAaAAAaAaAAAaAaAaaaaa = 165
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv = 172
Z16634652448482273138 = "HGpsHZoCBYzCRojROIBbnmWRBvovosRiTIWEihfmeqrdwdOBgfcFJFvSGqBVfxnhDQvpuZQWNwhruem"
l16634652448476207136 = "pXnUxMtJSQvWnBKeNUjDSZnXDsiRYYQaBbQALqHcmSdgdEbaKihFXGqBjYHVOvzLTLQrIfKLUJIulbL"
Y16634652448470013134 = 159
aaAAaaaAaaAAAAaaAAAAAaAAAAAAaaAAAAAaAaaaaaaaAAAAAaaAaAaaAAaAAaaAaAAAaAAaAaAAAAaAAAaAAAAaAaaaAaAAaaAAAaaAaAAaAaAAaaaaAAaaAaAaaAaaaaAA = "owTqUWevbFofKgxeKswMQSGjHEFpVmXlyJHciJPCAwpOBZpqMWmUNSrIrQLreUUREQbulOUGhEPXRDP"
q130 = 294
llIlIlIIIIlIIlIllIIlIlIIIIllIIIlllIlIllIllIIIlIlIlllIllIllIllIIIlIIIllIllIlllIlllIIllIllIIllIllIlIllIIIlIlIIlllIllIIIlIlllIlIlIl = "ksGACCqtihpdgfjSWNVFHcXJRZwfOidduCGGufTFUSiVSNjBsPhIqfzsNCXFlfRbSNRRzgTqYdvGTZY"
jXXEQyuvUoFhvtwoUKCbkzUsiglntcrzzamnWplxLqmfrWUrciaMvnAWBiYNCCMrzKGYYhUOzMMcQwi126 = 329
r124 = 340
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL = "PKDlMUzmkHkaNePUwefsFFSKAffqaEbkmiYuzixBqxWRBnbdnrVwoGOFrmDhGDDfVshrWHYllLZQowg"
reedUyrURIgrCvDMyLUddAwHtaHGEqNiSYwKjKHkgbnGRiiKJUFHfhyzLunzJWCSdMMMVmYChkHGXIM120 = "XZQEgUjAmQkDzxXTIsgSZwFKjJArSivpLSEgCuoOHsggBCBYuVVgTUyjtZtZXjkqQFThdtFwtuJmRfC"
x1663465244839378118 = "wMzRtaRPBLNftlKhEPhtDnYFitqIjEHjnFiVvcifZQbrXfTUNbtkxkKcFFJeQCCdXZlMagEoaeSRyAI"
KzxjjchavcnkfVssUEntzjRFmmEMHCQsdVYCXuBQuBODKecWarMdxXoadBZNknQjaNVELVrKmnQkhnF116 = 413
IMpoEhNfLkOlYIZggOjUScsDTBJHGFKJfqGMimDuhgESeykSESrEvnBhqKZXDdseaBnboQmCnfrBrCQ114 = "fzhGjzKgRJGSAGLUFPuJZoWUqkjvtXJTQPVbrhfzCEHLgBMudqlOGcsTqbWFaSsoAafkAscixUnCWyK"
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = "fEhnjBJPzjCrCslifJZCIXejRhzpSojryKQrfEfYgbarbDbRklQhgfOVqEQdnQFDghclMGoBHegCYtF"
lIlllIlllIIIllIIlllIllIllllIIlIIIIlllIIlllllIIIIllIIIlIIlIIIIIIIllIlIlllIlIlIIlIlIIlIlIIlIIlIIllllIllllIIIllIl = "rLjwEAhZeWwTODJtmmbrfjGmcKTZieJvwtDiJoOzRfOngYYYYWefTZAEfvgfPekUAikqRJjtLVZUFlM"
v16634652448323462108 = 642
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV = "fGSXpZDEfjpMmuvztBbYKUmtMmtxOLXzkMYjgPiTisyhdpietZWMpTKpQIHTSsSrpDCErUBRDjofPMm"
j104 = 893
IllIllIllllIIlIIlIIIlIllIIllllIIllIlIllIllllIllllIlIlIIIIIIIlIIIIlIIlIIlIlIlllIIlIIlIllIlllllIlIIIIIll = "YOAcpVigbwAqzWcbPKGxhmGvyxcqYtjWzECzcPzicfwXiTPccZDfspNjVnlISLkDmcepTDQwHgqLBqA"
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = "SvOabSvetBIbotEcNeWoMnUCNVnkkhIfIXzUzdqcYcccRprxwPRQChudqwGbMXEwqusxqfrtKQneVkg"
AaaAaAAaaaaaaAaAaAAaaAaAAaaAAaaAaAAAaAaaaaaaaAAAAaaaAAaAAAaAAAAaaaaAaaaaAaAAAAAAaaaAAAaAAAaaaAAAaA = "fwuJiRUPXQYCFiKVIWflxthewUmkQLKAVOnwUSoFhoJouKCebjhmPoqzfNAqwysOeWIEgaBZdWCXcRO"
IIllllllllIllIIIIIIlIllllllIIlIIIIlIlIlIlIlIlllIllllIlIIlllIIlIlIllIIIllIIIIlIlIIlIllIIIIlIllIll = "sPbmGJXjhRbTDOngVqDBYodkEsiwXCcxSScyhUSlCtRznolmCrquEJdydbUhEkdLDnsfVMPhskpFMOA"
lIIIllIIlllIIIIIlIIllIllIIIIlIIIllIlllIlIIlIlllIlIIlIllIIIlIIIIllIllIIllIIIllIIIIllIlllIlIIlll = 350
AcomEdMnWLgeGwdbMryxIJdYZILIZnqQUmTVRXzXUMvKOuQxXgPfVjSmhxRIWYLJDxcpgGJfuDrRNKd92 = "THiTSXXBmDNJerfrRRMUegkTzywAuLaytBxiPOMQjFtiiCAEcEfRntzAiOSzfjkXvKIOuSbWYIttbAf"
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = "GrIuoUOGUvaHTyvOynNfCsvSJhlyLxxwlRzAdqriCmgBSfXSOBfSZGzXIjvFGUrmcFshRPYWgdOISQE"
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = "gzLtDZRSmsqAZFZgyGuDEgJaMZXJzorVTesCkmQScDdVfOvtXFlfOHIlKzMaYSiBIFNKwWIjCNPnGZz"
yQeLMnwJQywrVFRzhHbAhYrfTUOtsOMlBbvYHRjFWsHeJhSzLpsFSGeVYowgRInwNfnQfRnmvAkWlSs86 = "wfIZiAxsWIBvIGngEXIxuwIzmUWAvlOicJLsjBKmDpGhykVZTKcthifUYRXidIwisFQgDNvqNJkUMRj"
e1663465244817222484 = "EKlJZkdGsLnUyZvCEBUfOIzHTdyaZFWxsuImsEBXhikiqNfZGmYTxeNmlHHtjdrveTDOOqtMyccTVRh"
aaAaaAaAAAaAAaaaaAAAAaaAAAAAaaaaaAaaaAAaAaAAAAAAaaAaAAAaaAaAaAAAaaAaaaAaAAAAAaaAaA = "xLrfsvqNFzPXpEZFTYKroCZbGyUpEiELNFRyaJAbmtRuAkvZqcgxskfaVqICVDYGJAdHXRyXLpAJDUd"
lIlIIllIIIlIIlIIlIlIIllllllIlIlIIlIlIIlIllIIIIIIIllIIIIlIIlIIIIIIIllIIllllllIlIl = "MLmeDBHXTjzqjyHmpuXJXoBBoXJDOQVIFvBXHYvgRerUvpaKVrQHBdczoGWvynBVGpqpMKOwiZoPbWe"
AaaAaAAaaAAAaAAaAAaaAAAaAaAAaAAAAAaAaaAaAAAaAaAAaaaAaaaAaAAAaaAaAAAAaAAaaAaAAa = "jWGwgDBVgGqBejKQsoGRHlKxoHLbLletfvqWEtHSLyvnVYRfzmJorpTTBYHQvbsISQZXcMTNFzEHMjW"
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK = 549
IIlIlIlIllIlIllIlIlIlIlIllllIIllIlllIIlllIIIIlIllIIIllIlIlIIIIIIIllllllIIl = 193
q72 = 582
J70 = 591
IIIIlIIIlIlIllIIIIlIIllIIllIIllllllllIlllIllllIlIIllIlIIlIlllIIIllII = 499
n1663465244806220566 = 45
IIlIIIllIIllIIllIIIIIIIlIlIlIIIlIlIllIllllllIlllIllllIIlIlllIlII = 314
IllIlIllIIllllllIllIIIllIIllIlIIIIlIIIIIlIlllllIlIlIIIIllIIlIl = "HnZgqgWSzvHiWIwPjJmAnWmbaihpGfABnaqRMDTagniLHXmKIRvXtFNTesEOPreOVjdCRJxGwYWvlNp"
tbCmuqlcrSoEsTFHPkNfoHRrXHUsJxZgIXlcaJFgFqvITCvKAqbFEoptldZinasjerrLwyLEUaAZxDK60 = 330
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC = "nqBucYMiCwaeAqTJgsOzVRtowumRlabrgWJZyfxAVklIxFktQfQpIxIRSITMdbOgKACQMXoXeLVOSKP"
lIIIllllllIllllllllllllIIIIlllllllIIIIIlIIIlIlIllIlIlIII = 564
T54 = "qlydbBLfBuddSUoOOojXLIzRWohgPaAJgKQhMcDXvJjAKXGZjAIJzszUVGWPTcXTaEiwLZljvUcewlR"
aAAAAaAAaAaaAaAaAAaaaAaaAaaaAAaaaAAAAAAAAAAAAAaAAAaA = 804
x1663465244799585650 = "NEWGoWQqRMpYhfpFjHuDolcxxaiQiCsVwviyubdFbUrvFTbXUtisOflJqagrKOTXFMTdycxkDpONJae"
p1663465244798964748 = "xDCjVotanSoDZOYLxcYzfBehTgtQooxmwezDYUCGWPOYFzdQekccJZlvgBXvKVPwAggeKgcISmdNayR"
hPJkfaqLXWSQLkgDteVNlbFBlaKFJpwwdamzSiMxZjHShjNPohzTDzWMKvCFzjeFrjAKqNIqrzFxODR46 = "CmTDDWEUjqgaDiJVNkRruZJQdjqGymHPPbAjGUgrgEIVBHGZodXZGcyMlutGPdRTXVetXaPxkrNTKBM"
k1663465244795495344 = 41
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk = 380
B40 = "LKsziaNhBtqEZJhLxrpvakIWIVNQnWwDVVroGUnOMqXjJaDmzDYdIiRLSsCSXyWHWPtjiREpgKaXSol"
IlIlIIlIIIllIlIIlIIIlIlllIIllIllIlIIII = 685
ExffDwWxPNByiEztllGfzTibGayXnhHTxkjAEopcEKRcfUblmtQTJXlLfzzrIWjJEoxALfFXuSKqEFn36 = "RPBgjSgLfLbCUYuijbaKLmfwPJFJLttYqxdHPsOmuoIouWguzTiFrUmxelvxKYvcVCMgIKSyjyyWvrS"
lIIllIlIIIllllllIlllllIIIllIlllIll = 272
G166346524479077432 = 365
aAAAaAAAAAaAAaaAAaaAaAaaaaAAAa = "YhvbtgyemrqBJQnPyIlGZMPwBGukwpBvJXeEIkUSNzmDfvslSfiRMNLbCINrXKczpvnprRYkHMeawiB"
llllIIIlIIllllIIlllllIIIIlll = 262
R26 = "HywdmQASxfDHzxbOVUEaVwuPyrZODVrNIyUYPLfUoZdgUYHNfKSouWDPmrUMnZMCOYxRZRvbauISarH"
PPPPPPPPPPPPPPPPPPPPPPPP = 762
XXXXXXXXXXXXXXXXXXXXXX = 799
d1663465244785904420 = 241
ChVqibdSwnRcIfPRJUyLCPJvhXwHwYZrqtghuoyWkZGyeKKLprFszAnfdShLapJmbRLLPCzNCbrUDDZ18 = 366
SYlXIjZIAIJmGKApsjDVzsgWPzhKEJhrziUystNeHkzEYHxnVqlIFmKnRYZOIWlgwZnIwndmHqfRdyc16 = "YbAWAgzKKCCRwclDGNQxwnxLtXIbqqXUlwdvFRjvNunBIKqHOJtZDNofiXjkBRnkrSmyHjJBXNrWMlz"
llllllIIlIIlll = "cMZnqFGUgKpPmVaAhGywiCzeRHIhiHlXgJNlOpQNSrpOfzJesLsqofIwOUduaJNnYYjxZJTjvhSJhtV"
AaaaaAAAAAaA = "elrnXXxxdhMtodIBAzXrPlHfVToTeDzvBNqDfqpQxkLccdnXiMVpeyhHhaZCyBjxMfFaBfJFyvrxcwX"
ZZZZZZZZZZ = "NgCtTeRIJeeLtUHuJTAdMddAsRzlKnObIixEGSoySqTzAbrrcRccUvpKaEhkuxmXZMHykTSkBBzWpwb"
qIoZKLWibCLaaLgALHbOvqlglLQnvrfoDzOYzljGhsxAdFBVSjaqwCjCmXtYukzaRVKOJzYbLouJqWF8 = 377
IIllII = 581
nSksNyayITDOLmhsUilrDuNgFjJtKdxSYaNjtLKgNVXihWmiLeyuFKsGNPeAwpQzrYrRewfqruvmrnk4 = "bpNUJslYfXBCiWGDuJGCudORCByqXSOoRWeuzCBJYFddkcaAyeSHwEcVEsZIgkdJSTZJLqUANUYrTix"
v2 = 360

import json
import uuid
import hmac
import random
import hashlib
import urllib
import stdiomask
import urllib.request
import requests, os, re, bs4, sys, json, time, random, datetime, subprocess
from concurrent.futures import ThreadPoolExecutor as YayanGanteng
from datetime import datetime
from bs4 import BeautifulSoup
import requests,bs4,json,os,sys,random,datetime,time,re
from rich.table import Table as me
from rich.console import Console as sol
from bs4 import BeautifulSoup as sop
from concurrent.futures import ThreadPoolExecutor as tred
from rich.console import Group as gp
from rich.panel import Panel as nel
from rich import print as cetak
from rich.markdown import Markdown as mark
from rich.columns import Columns as col
from time import sleep
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from bs4 import BeautifulSoup as parser
h='\033[96;1m'
YY='\033[1;32m' 
yKyhJvKSfAaAnjznLnHwAxSJqIFRfIBmvRdzPhbVPBJcagzrhMxwgAYhUOGMUHcPxYMZRFtnKVKayLD3='\033[1;31m' 
lIll='\033[1;33m' 
AaAAa='\033[1;35m' 
lllIlI='\033[38;2;255;127;0;1m' 
d166346524476660187='\033[0m' 
aAaAAAAA = '\x1b[0m' 
def logo():
	print(f"""
══════════════════════════════════════════════
▄█    ▄      ▄▄▄▄▄      ▄▄▄▄▀ ██  
██     █    █     ▀▄ ▀▀▀ █    █ █      
██ ██   █ ▄  ▀▀▀▀▄       █    █▄▄█      
▐█ █ █  █  ▀▄▄▄▄▀       █     █  █    
 ▐ █  █ █              ▀         █     
   █   ██                       █      
                               ▀   [{yKyhJvKSfAaAnjznLnHwAxSJqIFRfIBmvRdzPhbVPBJcagzrhMxwgAYhUOGMUHcPxYMZRFtnKVKayLD3} • {aAaAAAAA}][{lIll} • {aAaAAAAA}][{YY} • {aAaAAAAA}]
══════════════════════════════════════════════
[{yKyhJvKSfAaAnjznLnHwAxSJqIFRfIBmvRdzPhbVPBJcagzrhMxwgAYhUOGMUHcPxYMZRFtnKVKayLD3} ! {aAaAAAAA}] CodeBy     :  AMELIA-XD
[{yKyhJvKSfAaAnjznLnHwAxSJqIFRfIBmvRdzPhbVPBJcagzrhMxwgAYhUOGMUHcPxYMZRFtnKVKayLD3} ! {aAaAAAAA}] WhatsApp   :  082292114573
[{yKyhJvKSfAaAnjznLnHwAxSJqIFRfIBmvRdzPhbVPBJcagzrhMxwgAYhUOGMUHcPxYMZRFtnKVKayLD3} ! {aAaAAAAA}] SUPORT     :  Axis/Tri/Xl/Wifi
[{yKyhJvKSfAaAnjznLnHwAxSJqIFRfIBmvRdzPhbVPBJcagzrhMxwgAYhUOGMUHcPxYMZRFtnKVKayLD3} ! {aAaAAAAA}] Version    :  BETA
[{yKyhJvKSfAaAnjznLnHwAxSJqIFRfIBmvRdzPhbVPBJcagzrhMxwgAYhUOGMUHcPxYMZRFtnKVKayLD3} ! {aAaAAAAA}] STATUS     : [{YY} ✓ {aAaAAAAA}] PREMIUM [{YY} ✓ {aAaAAAAA}]
══════════════════════════════════════════════""")
def alok():
        logo()
        print(' [%s1%s] Informasi Tools'%(YY,aAaAAAAA))
        print(' [%s2%s] Hubungi Admin'%(YY,aAaAAAAA))
        print(f'══════════════════════════════════════════════')
        ifymbaSGTiXwuvDwXJhEPVXrPGzkFwzVbnfcPmbkDVCjkSdGZktcgWTflOuyKdYkipAarRFkfBwwzct9 = input(' %s(%s?%s) Choice : '%(aAaAAAAA,lIll,aAaAAAAA))
        if ifymbaSGTiXwuvDwXJhEPVXrPGzkFwzVbnfcPmbkDVCjkSdGZktcgWTflOuyKdYkipAarRFkfBwwzct9 =="":
            print(f" {aAaAAAAA}[{yKyhJvKSfAaAnjznLnHwAxSJqIFRfIBmvRdzPhbVPBJcagzrhMxwgAYhUOGMUHcPxYMZRFtnKVKayLD3}×{aAaAAAAA}] Sorry, it is wrong...!");time.sleep(1);alok()
        elif ifymbaSGTiXwuvDwXJhEPVXrPGzkFwzVbnfcPmbkDVCjkSdGZktcgWTflOuyKdYkipAarRFkfBwwzct9 in["2","02"]:
            print(f'\nAnda Akan Di Arahkan Ke Admin')
            print(f'{YY}1')
            time.sleep(1)
            print(f'{YY}2')
            time.sleep(2)
            print(f'{YY}3')
            time.sleep(3)
            print(f'{aAaAAAAA}[{YY}OPEN{aAaAAAAA}]')
            os.system('xdg-open https://wa.me/6282292114573?FFFFFFFFFFF=Assalamualikum+Bang+Saya+Ingin+Membeli+Sc+Ini');time.sleep(2);alok()
        elif ifymbaSGTiXwuvDwXJhEPVXrPGzkFwzVbnfcPmbkDVCjkSdGZktcgWTflOuyKdYkipAarRFkfBwwzct9 in["1","01"]:
            os.system("clear")
            time.sleep(2)
            print(f'\t           [{YY}+{aAaAAAAA}]  Informasi Tools [{YY}+{aAaAAAAA}]')
            cetak(nel('INI TOOLS UNTUK CRACK IG,DAN SC INI PERMANEN ,SETIAP UPDATE ANDA AKAN DI KABARIN MELALU GRUB WA ADMIN,CRACK IG/HACK IG INI MENYEBABKAN DATA/KUOTA ANDA TERKURAS,JIKA ADA PERTAYAANLAIN SILAHKAN HUBUNGIN ADMIN TOOLS TERIMAKASIH'))

if cccccccccccc == '__main__':
    alok()


e166346524477894071 = 635
aAa = 532
AAAAa = 353
t7 = 65
A9 = "KMTMdHnnpIvMGTGsIHwuIpgkvPcuthqAmgfYybTKfnIEHWtlBnBuobNJofoueezSOMmdrwrwawDVdOE"
AaAAaaaaaaa = 202
t1663465244782959513 = 545
M15 = "szMCBLutjETSbTXAXfqlXeKMczUybSWxZEhQZVWdUunqsPNBzwePyyPAGiNhCGGnsIRSxjovlZeQQPQ"
lIIllIIlIlIIlllII = 380
VVVVVVVVVVVVVVVVVVV = 121
nnnnnnnnnnnnnnnnnnnnn = "girTcZeSWkFzVdyjgyuUWXZTwqxfjCAyNifKZKGJirldqBKLHWVGzBxIyvqSjkmrWjjCNaKgbMUJshT"
L166346524478660323 = 526
B166346524478722125 = "IvAPYnEAOeWrWzVATVNtuRohIcRDqaYWeDNyqhFXleWFdIOpozVbMZWsEDMaJSdEANORGLCBKGUtyRp"
mDkZcXgoPemAJIpBexHqVyTyaTHJVtbIUCRNMREUeHZpgBuywWLdrGQjyNOnwOPMbFYZrAnJKWswKwn27 = "aCEdrYvwdzCawtXfyCTSsLVqEoUEiFozLQeAEJnCDZMBiVcJIkdOLvZLcnVczRkijGfHRPcKHXTPMvV"
NmEuyqwrrspHaEreEKSIreDWYQYfRLyCcempdFLElgPHtwfVeoYosSNTdgeGdKseNObRBnNjlAaviWn29 = 517
MTazeuvDycoTUddwFMmcqjOVfuWAEmCDSBDnPnpoJaljCpGgSZOKRMzOsaqvveRzNxuVtWyIcytwYqR31 = 555
C166346524479085233 = 721
aaaaAaAaaaAAAaaAAAAAAAaaaAaAaaAaaaa = 394
lIIIlIlIlIIlIlIllIIIlllIIllIllIlIIIlI = "mjFuzToGgacMtMVGKxLWsmXOuucwrSIlXUlswdRPDYQoYKeQBGnjuGdqEVrQJmwsIfWkHTRKFuRESDq"
ggggggggggggggggggggggggggggggggggggggg = 348
lIlIIlllIIlIIIlIlIllIlIllllIlIIlIIlIIlIIl = "LqrQKDrpLJGQmwPIhxFDahTdavBCQoZAneRwlEtoPyOUjqyUiijsfoCArIJZqtynkvtCSkrRluNXEbV"
xFAyPoJQHCFYuXTGMANMGowVGJjLPbzfenzyZuFjorPimUPyXuJQMaoIPzXzzxhXKakAvvrWPbHhasN43 = 222
ibViikJgYBzlMsEyUBFHNcBxKRmoHeVmOZeQTtZtfZcQYpDkrBXBanHaYFWjrZyvfLzWUiulAsgMtJZ45 = "UfZacOccGMDxoqsDCghsvCvcdziyEtusTyjSnnkxGCiLXujgROLXLiJzblLxhaSNnGBvYxkApohzwZY"
sjFiQToKaWFAboDNYRUffsvOezYUTzhkkXsrWHHWEXJmtYKnCVRrdeMHCeFmIiGUVFpLajXEYnPOuat47 = "SCdnnppQlecqvwAyNpYGVVIKHEWARtqDvtpJOJLnVpUxXDdiuOrmiUuhSXhqCZIKdfrEFqLUvqgjLmu"
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = 477
N1663465244800133551 = "sonbKldCFWPWPLDERiQoOCovBYALtfSKyMAElqUHRuujYhAejChdoRcGiQtHOZvoKKqVMlXHfpTBpgV"
aaaAAaaAaaAAaaAaaAaAAaaaaAaAaaAAaaaaaAAaaaAAaAaaaAAaa = 419
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj = 253
P1663465244802475557 = "jgpDksoYbKZxKteQRoFaareUAnTKeQSxVXZtTWLrrgSHDQfaLEROwvyiMlCkaBpsGcBCtWpsQfFEVFN"
F59 = 93
E166346524480365261 = 535
IlIIlIlIIIllIIllllIIllllIIIlIlIIIIIIIIllIlIIIllIIllIIIIlllIIIII = "vqMgzdIHjaCHvOzBKVyZResZrsASuUOwPXPvPWPLpVhLTSYRwSJgvUWUlGqFKEXPOWnTJAIdsYABkAF"
AAaAAaaAAAAAaaAaaaaAaAAAAAaaaAAAAaaaaAaAaaAAaaAAaAaAaAaaaaaAAAAAa = 325
ZaKawfXtioOhrapWTqYpvJwLneEOQaYJlgRTBUpFKFIiyeiGFfcILtltgBVcnUloVJYVanLKKlbECzQ67 = "bwdZGdmPcmmpafvABaqShDVuFogWUeGahnjtAHHYMrevaoXuCWBqkwxBoygAeNQSjahNeYNDoCMgtNU"
llIlllIIIIlIllIlIlllIllIIIlIIIIllIIIIlIlllIIllIlIIlIIIlIlIIllIIlllllI = 375
AAaAaaAAaAaaAAaaAAaAaAAaAAAAAaAAaaAAAAAaAAAAAAaAaaAAAaaaAaAaAAaaaaAAaaA = 509
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz = "MhpKsFifiCrrtVvqgcVQmnAoBIlPYnRLLNsvVHlgRKYoVDncRhNuChVRmaEVhVQEdaWXbbcewbhVYLe"
IIlllIIllIlllIlIIIIIlIIIIllIIlllIIlIlIIlIIIlllIllIlllllIIllIllIIIIlIIllIIll = 310
AaAaaaAaaAAaAAaaAAaAAaAAAaAaaaAAAaAaaaaaaAAaAAaaaAaaAAaAaaAaaAaaAaaAAAaaaaAAA = "coQXodtUVmsYTsBwFHACJOzqDAgybuBgMsAVxMWTlQbJExGHqLoThIaRKgLQPZsYMvCJpvVNOzHpVeq"
lIIlIIIIlllIIIlllIIlllIlllllIIlllIlIlIllIIlIlIIIIllIlIIllIIIlllIIIllIIllIllIIII = "yxsClDwaxZfqtEvBicVjgNAaCoASuZYupVVrjRtwuUczzwTERdNAjyBGptgZEHsxceaGmbmwLHLimUu"
b1663465244814605281 = "GXemMKXOtyReFkkxvplXSGFopeyfanTbCkVduqvFrRSuiIYBpNhhEijnHOTzERljppdANtQfETtgDRH"
XZNMgNOtztukeMhjfwXeAOvEtnQKklSmoWDbKKGymBfqWpUUEHHMcIxanEaaKzBBDvBnQmQBRGpTOpm83 = "trPRBqcRXTATYGoZcrTdXrZAzeeRgyGaxtdcbwBsJvVGAIRQaEshYsrhxLxPizfbuVHZVdfHqPKZGea"
M85 = "IPRZKuiOHLzaacqgyxZFYkDdwroMlxGoPyJOgPlJcLFUIaiTcmkokKrNqsVLDSJTjohONSmkJkDiYNJ"
AaaaAaAaaaAaaaaaaaaAAAaAaaaaaAaaAAAAAaaaAAaAaaaAAaaaAaaAAAaaaAaaAaAaAAaAAaaAAAaaaaAAaAa = "mvGVcHyrZyXVQCsAStMKFsGaAMgHOFGaGPFKduCpxOAMwOQgbMmDJQYgDICqnDSCDeYtMkvjXgEKDSc"
llIlIlIIlIllIIlIlIIIIlllIIIlIIlIlIllIlIlIIllllIIlIIIIIlIIIllllIIlllIllllIIlIlIIlllIlIIIIl = "xgAjDjdPuPTBstKOWOlRGGpxKzQOfYEXWddJClhcOnpTPVehZubJMFyloOmoFanOQZyrIAVWaPYgQJV"
d91 = 806
tOtVxCPsWzuJDgTCpuGRPLedSjGGbFReJqMgVWYGyExvZEOAdnJeNxlrvwyVdIszYMThqEAmLUurBdQ93 = "XAhjGPWKYKJtMqgkHtNjRMFGzhSJYTlmRdOqgQJVGZmNbcKvLafJlccnwymazWMTKQGwKLqqrdoLwWo"
R166346524482461495 = 396
SLSJNhIPZNBKsiaDvGjdfoKonKMOBVqsSJSVPRJiPUeviJKQnYyvNIxkacUWSUWoVlwmwmnaWqAJPJd97 = "sAYROAOzKvYvbnfvbSiYHIGrxgDnVFbGFfaeprVjyJymPMOwGPxUkRfYixZNhPQbZQGwEhZmxNEIaBo"
E99 = "STnhlbJfeFtRTeVANSKrIjmeEJEomxuzfpHyVLLhIMxDffYtXkiIOKxsUDfUSfTIAnCJPoviZyqwCKJ"
I1663465244828846101 = 504
AaaAaaaaaAaAaaAaaaAAAAaAAaAAaaAaAaaaAAaaAAAAAAAaaaaAAAAAAaaaAAaaAaAAAAAAaAAaAAAaAAaAAaaaaAAAAaaaAAaaaaa = "SYscAMuAveCEWdHQzQLeFPXbsjvfDMADKQIOenIGKnCCRczmrimuekvRdjfpmYXfmRDqAbgUnFLpMia"
i105 = 149
m107 = "nxYzCRdycpALpWfshXrMMwFdttzQqyxOfQUQZgPrWSlnwLxSaXTJeZcyexSiSVODhMgXfZrFCxLmpxV"
IllIlIlllllllIIllIllIIIlIIlIlllIIIIllIllIIIIIlIlllIlIIIllIlllIIIIllIllIIIIlIIIIIIlIlllIlIlIIIllIIlIlIllIIIllI = 88
IlIlIIIlIllIlIlIlIllIIIIIlIIlllIlIIIlIIllIllllIlllIlIIIlllllIlIIllIIlIllIlIIlIlIIlllIIIlIIlllIIlllIlIIIlIIllIlI = 218
IlIlIlIIIIIIlIlIIIIlllIllIIllIlIlIIIllllllIlIllIIllIIlllIIlIlIlllIIlllllllIllIIlIIIlIIlIIlIIllIllIIIlIIllIlllIlIl = "lQpZhaCWnmjDhpKVTOfiXQqqOsHjfGBWcjvgkIjJqAZqkplywpANcvltsCTpExAqiSQtrBWDKOOPFvo"
a16634652448376672115 = 588
AaaAaAAaAAAaAaaaAaAaaAaaAaAAaaaAaAAaAaAaAAAaaAaaAaAAAAaAAAaaaAaAAaaaAaAaAAAaAAAaaAaAAaaaAAAaaaaAaAaaaaaaaAaAAAaAaAAAa = 574
I119 = 298
IIIlllIIIllIlllIIlIlIlIIlIIlIIlIlIIlllllllllIIlIllIIlIlIllIllIIIIIIIIIIllIIIIIllIlIlIlIIIIIIlIlIlIIIlIIIIIIIIIlIIIIIlIllI = 110
q123 = 365
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = 312
z127 = 488
n16634652448443482129 = "oOItENmUZnGBqqjQkrZtuVEbyvsdcYBZGgDPHJeIaGsoksrTfNVbUfXhiomnovFqmfiBMtnzpadBZpw"
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE = 114
IlIlIlIllllIIllIlIIIIlIlIllIllIIllllllIIIIIIllIllIIIlIlIlIIIllIlllIIIIlIIIlIIlIIIlIlIIIIllllIIlIIlIIlllllllllllIIlIIlIllllIllIllllIII = "zzwvWKybuISAVUHvxnECfYPtebElQVezeoUeHiKBLMKvTfEdWrJHluAwDhIboDPausGrBJPpNoTNhrX"
E16634652448470743135 = 855
W137 = 343
O139 = 468
S141 = "XZXDeakaXpBPGOnnGiFmEzhAwIiDWVKJBwfzLPpFalYIvTUgLlszGibeHmrTTMZogHJiBLHlLPlFfwf"
AAAAaAAAAaaAaAAaAAaAAaaAaAaaAAAaAaAAaaaAaaAAaAAAaaAAaAaaAaaaaAaAAAAaAaaAAAAAaAAAAaAAaaaAAAaaAaaAaaaAaAaAaaAAaAAaAaaAaaaAaaAAaAaaaaaAaAAAAAAAAaa = "aTdliQbKLqVmvJjLzxClVfkvVUxhCCxrEYvORAyyJdUbHIXHOttCZAdiPoWwZOjDCAcOxTkbmQsNord"
aAAAaaAAaAaAAAaAaaaAAAAaaaAAaaAAAaAAaaAAaAAAAaAAaaAAaAAaAaaaAAaaaAaaaaaaAaaAaAAaAaaaaAAAaAAaaaAAaaaAAAaaaAAAaAAAAaaaAAAAAaAaAAAaaaAAAaAaaaAaaAAaa = 127
ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt = 382
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn = 243
C151 = 342
IlIllIllllIIIIlllllIIIlIlllIlIlIlIllIIlIIIIIlIllllIIIIlIIlllllIlIIlllIIlllllIllIllllIlIIlllllIlIlIllIllIIlllIlllIIIIlIIllIIIIIIlllIlIIIllllIIlIllllIIIIll = "xLgROrYyDsolhNwEZiqIYdkHQbQjXSRqEUQtVUYjbErKUgmSCuuquTouZLoWvqNYeMEHGUxnexxBdBk"
AaAAaAaaAAAaaaaAAaaaAAaAaAaaAAaAaAaAaAaaaaaAAaAaaaAAaAaAAaAaaAAAaaaAAaAAAAAAaaAaaAaaaaaAAAAaAaaaaAAAAAaaAAaAaAAAaaaaAAaAAaAAAaAaAaAaAaaaAAAAAAAAaAaAaaAaaAa = "ZLBtQmKrXDDhjFNGYmxzogIIqbjwBrZwYmNzUNZgYWtQkoadtMNNPjxkxJagVihpLBqmqdJlTAZgSMo"
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg = "aTRcWgTFvwePJKTnkcjBMyyqXWclHZKdjFBhCInrQbWcFJOroJUjlbAgsqghMfHqubEoQfPLMyPGnnh"
MncDrQNWKahKaFTwptXKlrdQiJDawYosSSMHntAQqjiXdDcrkdHJGEcDmayQCeTitKxtSBwTAFKuPmj159 = 294
IlIllllIllllllllIIIllIllIIlllIIIlIllIllIIIlIlIIllIIlIIIIIIlIlIIllIlllllllIllIIIIIIIlIIIllllIlllllIIIIlIIIIlIlIllIIIIllllIIIIIlllllIIIllIIIIIlIlIIlIllIlllIIIlIIIl = 292
t163 = "LhxmNyeAAdBzCEjexeKSUvCgTUPwAsBzXVgeNoMzEhRSbluBylhcoxayXIZjTRnJjJCVqIOmbdxUgAx"
lllIIIIllllIIIlIIllllIllIlIIlIIlIlllIllllIIllllllIIllllIlllllIlIIllIlIlIllIIIIlIIllIIIllIlllllIlllIllIllllllIllIllIIIIlIllIIllIlIlIlIIIlIlIllllIIlIIllIIIIIIIIlIllIlI = "kIByUwmNEfhkQkDyBgwhxDBiceZheRBvDyGhLDHomkvpEZDEKWPdgpWXKUVneWFOLqhOEpeqvHVjLTn"
aaAAaAAAAaAAAaAaAAaAAaAaaAaaAaaAaAAaaaaAaAAAAAAAAAaaAaAAAAAAAAaaAAaaaaAAaAAaAAaaaAAaaaaAAAAAAaAAaaaAAAaaaAaaaAAaaAaaaaAAAaaaaaaAaAaaAaaAaaaAaaAAaaAAAaaaAAAAAaAAaaAAAAA = 194
CfALALPDvDgUUdzxTKfhOCifHNUlMitySpPxAOUeZYnnXgwZoAhOSqVxWuJiJXwoVDMwfQkbTfFDAAX169 = 195
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK = "iNJMEqKVMEyoSXOirQzKMpJBfKhDmuKTTxgAKBULyJFlOkAXkuMxtCbZEYRzHqTwGegNyxcvFhKFtek"
lIllllIIllIllIllIIIIlllIlllIlIlIIIIllIllIlIllIlIlIlIllIIIlIllllllIIIlllIIIIlIIIlIllIIllIlIlIIlIlIIIllIIIlIllIlIlIIlIllIllIIIIIlIlllllIlIlIlIIlIllIlIIlIllllIllIIIllllllIIIIlI = "QYmGqVSHXvcLXUDQgnyIWTMLHFaxKebinMKhgcPWGTIDouAOUfeYYePWudtGpGfXzTfWIxFFQtgpBTr"
KvfEaVSXXVZGwPiIsqeKgYSCPSNAUUpxgtQPoxCOpKPArkFDafqsOUdhnNiTjVhjRgBpMiYKAzDaeyT175 = "SCfKykZGuZXuZbZbVtsPvUyNOMCqJzuQLbwAjIjRzhVvPJpBsUBimKXHsLyFkGjPYefEmDaHDCocJKI"
pLuNMFcWvsJYTyAQhyHJYCEZFwDjUBuWPyMahOmjeczpkGoOvXynHluWfwcQjBohGUgWloObgnMAgDh177 = 240
y16634652448740501179 = 502
IIIIlllIllIIlIlIIlIlIIIlIlIllIIIllIlIllllIlIIIllIIllIllllIlIIllllllIlIIIIllIlllIIllllIlIIllIllIlllllIIlllllIlIIIllIlIIllllllIllIlIIIllIlIIllIlllIIlIlIllllIIlIIIIllIIIllIllllIIlllIlI = "fycddPQoxaXdCcUmfYCBMitHZmQuqNdTwcDEnzFCltvtznigsdFJOJqMEtzfKTBubpBkPmuxxxUPklm"
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = 282
h16634652448792436185 = "usjPDOEhByOApIWxmiVTtkGlVcxarkuPrnFXrDiVLgZrvWqPTWclkrvbRUElwXXAHaqTRVSDfVlCmyK"
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = "bFzyHQvIVszNBLHXdhvkrzCklHtOBLrNCJIMwQDYipwNLSxhdKlNQoexuqHdyvKsmoLBifwPPYVLGbr"
WivzLhYgMFaHdtWiuMupsUKFsIMVGNWUaXuBPnvjBwngEpsJHhEtlCRYJHzpTFIpONPTXUHBpYHzUrB189 = 253
ZxKNWIovKLOGCWDwTSAQamoVYOLtmoPGnylXgHxFibJrAfCNrhHZLWSrCibqoMiUaLUMzFKBsIQVYmC191 = 129
AaaaaaaaaAAaAaAaAaAAaAAAAAaAAaAAaAaAAaAAAaaaaAAaaaAaaaAAaaaAAaAaAAaAaaAAaaAaaAAAAAAaAAaaAAAaaaaAAaAaaAaaAaAaAaAAAaAaAAAaaAaAAAAaaaAaAaaAaaaaaaAaaAAaAAAAAAAaAaAAaAAAaaaaaaAAaaaAAAAaaAAAAAaaaAaaA = "PTdllUpFRBMFkfKdrHKzQOayNRCxEUFGqSGjtPYoQAWRJJScnrCMXRSVxUKhTMevWOphieqwBIYyWGw"
aaAAaAaAaaaaaaaaAAaAaAAAAaAaaaaAAaAaaaAaaAaAaAaAaAaaAAAAAAAaaAAAAaaAaaAAaaaaAAAaAaaAaAaaaAAaAaaaAAAaaAAaaaAaaAaAaAAaaAaAAAAAAaaAaaaaAAaAaAAaAaaaAaAaaaaAaaAaAaAAaaAaAaaaAaAAAaaAaaAaAAaAAAAaaAaAAaA = 350
aAAAAAaaaaaAAAaaaAaaaAaaaAaAaAAAAaaaAAAAaaaAaaAaaaAaAaAaaaaaaAAAAAaAAAaAAAaAaaaAAAaaaaAaaAaaAAAaaaAAaaaAaaaAAaaAaAaaAaaaAAAAAAaaaaaAaAaaaaAaaaaAaAaAaAAaaaaaaaaaAaaaaaAaAaAAAaAaaaAaAaaAaAaAaaaAAaaaa = "hwAspgkEJNASWhVelWjkCkptUvGIQLnLHnaKsAoPiGxZlfScicJaxEzVPGmGzGFCMaaZHzZjlnZlKaW"
txBIIlQNuKxEETFgTKejRyCCJDtmqmjOOIMjCYeetHEyVALYkBEBvDttQVkYKkIZxdtEmXZVbbXYCHO199 = "HVvvpsqqRBhvsHaQcemkGCkCwjtpirrwVhzXHBYdrYOiUPOyXnLdiKMveoeZreGYlNkTvzRVdNzpWQr"
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM = 335
V16634652448937993203 = "ApRDtcYFxzdTsZLYcfANaBjmodSLgrRBIsTIqqoFOfWcSOErDFvqROzXfntlEzazONwrUocgrvNzZxl"
b205 = "CdvVYDUJJTWcMNXIBrenmmRaebbsfARsCGOZOdltYDoIlaGAkMMIXzgnKHVeBxcwpEzflQsNEKfYhuD"
ssgVAydZFftkQGPonXadyIIKnrIUqZCysCcrnyCMHsumSNkylBlmnnazPXtkyPtApEDGckLyKIwbyrQ207 = 340
j16634652448970897209 = "DsxjiZChtYyFsyXPBuPWrbIobfkOeEAAZDawCrXnquDNwQIZOhelBXAOPnkBwHHGLTmgiwhdrgzicFa"
U16634652448976588211 = 307
lllIIlIIIllIlIlllIlIIlIIIIllIIllllIIIlIlIlIlIlIIIllllIIIIlIIIIllIIIIlIlIlllllIIlIlIlIIllIllIIlIIlIIIIIIlllIIllIIlllIlIllIIllllllIlIlllIIllIlIIIllIIlllIllIlllIllIIllIIIllIllIlIlIlllllIllIlllIlIIIIlIllIlIllllIIIlIIl = "uvAPGzHdQUppgAPQZSLoyFGwRZgSaEfyIicQCvcMoFxnEuGUSVBhOgYEmoZIHMwofGITZxXAuuQWfXJ"
g1663465244900585215 = 636
v16634652449018397217 = 427
lIlIlIllIlIlllIlIIIlIlIIIIIIIlllIllllllIlIllllllIIlIlIIlIllllIlIlllIIlIllIIIlIllIIlIIllllIllIIllllllIIIlIlIllIllIIlIIllIIIIlIlIlIIIlllllIllIlIlIIIlllllIIlIIIlIIIllIlIllIIlllIIlllllIllIIIlllIIIIIllIIlIlIlIIlIIIllIlIIIlIl = 152
AaaAAaAaaaaaAAaaaAAAAaAaAaAAaaaAAaAAaAaAaAAAaAaAAaAAAAaaAaaaaaAAaAaaAaaaaaAaaaaaAAaAAaaaaAAAaaAAaAAaaAAaaAAaaAaaAAaAaaaaaaAAAaaaaAAAaaAAAAAaAaaAaaAAAaaAaAAAaAaAaaAAaaAaAaAaaaAAAaaAAAAAaAaaaAaAaaaAAAAAaAaaAaaaaaaAAaAaAaAAA = 766
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = "WMRbwAmlhMlHCtEbEiCMpyaeUADZDqMkSYPFxbyEVhFKIPBXyrutGtYUSpMbwjjGayvyaMFcgRtEvrX"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = "UGvXYBlAycNVoqDVzaObqQrzhvaLDfILQthnIjALlsLbpFWvxtzVUUzleTupvNDMuJTPgUevhddvFkK"
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg = 824